version: '3.7'
services:
  web:
    build: djportfolio
    #command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn djportfolio.wsgi -b 0.0.0.0:8000
    volumes:
      - ./djportfolio:/code
    ports:
      - 8000:8000
