# Generated by Django 3.2.6 on 2021-08-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('slug', models.SlugField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('year', models.IntegerField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-year',),
            },
        ),
    ]
